UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q1-sherbrooke.mp3' WHERE question_text = 'D''après le dialogue, quelle est la raison principale pour laquelle Marc souhaite s''installer à Sherbrooke plutôt qu''à Montréal ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q2-train.mp3' WHERE question_text = 'Quelle annonce la conductrice du train fait-elle aux passagers concernant le retard ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q3-immigration.mp3' WHERE question_text = 'Quel jugement l''intervenante porte-t-elle sur les programmes d''accueil des nouveaux arrivants francophones hors-Québec ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q4-satellite.mp3' WHERE question_text = 'Selon le chercheur en astronomie, quelle est l''implication majeure de la découverte d''eau liquide sur ce satellite ?';

UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q17-meteo.mp3' WHERE question_text = 'Selon le bulletin météorologique, quelles consignes de sécurité les autorités émettent-elles pour la soirée ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q18-syndicats.mp3' WHERE question_text = 'Quelle est la réaction majoritaire des syndicats de la logistique face à la mise en place d''entrepôts automatisés ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q19-musees.mp3' WHERE question_text = 'Selon la directrice de la galerie, comment la crise sanitaire a-t-elle redéfini le rôle des musées d''art contemporain ?';
UPDATE public.questions SET audio_url = 'https://ifbbwbyxdjxsbuilzzig.supabase.co/storage/v1/object/public/questions-audio/co-q20-puces.mp3' WHERE question_text = 'Quelle est la critique éthique majeure formulée par le neuroscientifique à l''égard des puces cérébrales grand public ?';
